name: emotiontok
description: A new Flutter project for emotional venting.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  google_generative_ai: ^0.4.5 # Gemini API
  shared_preferences: ^2.2.2
  vibration: ^1.8.4
  intl: ^0.19.0
  signature: ^5.5.0
  image_picker: ^1.0.7
  table_calendar: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
