name: emotiontok
description: A new Flutter project for emotional venting.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  google_generative_ai: ^0.4.7 # Gemini API
  shared_preferences: ^2.2.2
  vibration: ^3.1.5
  intl: ^0.19.0
  signature: ^5.5.0
  audioplayers: ^5.2.1
  image_picker: ^1.0.7
  table_calendar: ^3.1.0
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  csv: ^6.0.0
  local_auth: ^2.3.0
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/sounds/
